spring:
  rabbitmq:
    host: 172.24.185.54
    port: 5672
    virtual-host: /
    username: admin
    password: admin123
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 0